@GlobalExceptionMiddleware_HostAddress = http://localhost:5116

GET {{GlobalExceptionMiddleware_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{GlobalExceptionMiddleware_HostAddress}}/api/test/
Accept:application/json

